### ISSUE TITLE
read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by obliqueRotationMethod** [onfoot/homebridge-shelly-shutter#10]
I'm receiving the following error when trying to start homebridge with this addon enabled:

> TypeError: Cannot read property 'indexOf' of undefined
>     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:120:12)
>     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:955:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)

configJSON:
{
  "bridge": {
    "name": "HomebridgeTEST",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-100"
  },
  "platforms": [{
    "accessory": "shelly-shutter",
    "name": "maxRolladen",
    "ip": "192.168.178.61"
}]
}

Platform: Ubuntu 16.04 on Raspberry 3
homebridge-shelly-shutter@0.0.8

Deleted the cache and removed all registered devices in homebridge, still the same issue

Previously I had the other Shelly-plugin installed and it worked for a couple of minutes. Then my shutter completely rolled up due to unknown reasons. Now after an disassembly of the shutter hood and recalibration the motor, I have an slight mistrust in the Shelly-addon (while I still think the motor is at fault)

**Comment by onfoot** [comment]
That's really odd. Can you tell me what version of node you have?

**Comment by obliqueRotationMethod** [comment]
```
node --version
v12.14.1
```

**Comment by onfoot** [comment]
Actually you're supposed to put in the accessory into "accessories" section, instead of "platforms". ;)

I probably should've been more clear in the docs!
